#!/usr/bin/env bash
set -euo pipefail

# Migration: Intel lpmd
# Host: deimos
# Generated by scripts/new-migration.sh
#
# Keep this migration idempotent. If a step truly needs elevated privileges,
# call sudo only for that step instead of running the whole migration as root.

echo "Installing and enabling Intel lpmd for better power management on Intel CPUs"
if ! pacman -Q intel-lpmd >/dev/null 2>&1; then
  sudo pacman -S --needed --noconfirm intel-lpmd
fi

sudo systemctl enable --now intel_lpmd.service
