[General]
DisplayServer=wayland

[Wayland]
CompositorCommand=weston --shell=kiosk
SessionDir=/usr/local/share/wayland-sessions,/usr/share/wayland-sessions
SessionCommand=/etc/sddm/wayland-session

[Theme]
Current=pixie
