exec-once = uwsm finalize WAYLAND_DISPLAY DISPLAY HYPRLAND_INSTANCE_SIGNATURE XCURSOR_SIZE XCURSOR_THEME
exec-once = uwsm app -- /nix/var/nix/profiles/nix-system/bin/ashell --config-path /home/kevin/.config/ashell/config.toml
exec-once = uwsm app -- mako
