hl.on("hyprland.start", function()
  hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
  hl.exec_cmd("uwsm finalize WAYLAND_DISPLAY DISPLAY HYPRLAND_INSTANCE_SIGNATURE XCURSOR_SIZE XCURSOR_THEME SSH_AUTH_SOCK")
  hl.exec_cmd("uwsm app -- quickshell --no-duplicate --config deimos")
  hl.exec_cmd("uwsm app -- hypridle")
  hl.exec_cmd("uwsm app -- tailscale systray")
  -- hl.exec_cmd("sleep 10 && uwsm app -- librepods --start-minimized")
end)
