bind = $mod, Return, exec, uwsm app -- foot
bind = $mod, Space, exec, uwsm app -- fuzzel
bind = $mod SHIFT, Q, exit
bind = $mod, F, fullscreen, 0
bind = $mod, V, togglefloating
bind = $mod, P, pseudo
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod SHIFT, J, movewindow, d
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, L, movewindow, r
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bindel = , XF86AudioRaiseVolume, exec, uwsm app -- wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, uwsm app -- wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute, exec, uwsm app -- wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86MonBrightnessUp, exec, uwsm app -- brightnessctl set 10%+
bindel = , XF86MonBrightnessDown, exec, uwsm app -- brightnessctl set 10%-
bindl = , XF86AudioPlay, exec, uwsm app -- playerctl play-pause
bindl = , XF86AudioNext, exec, uwsm app -- playerctl next
bindl = , XF86AudioPrev, exec, uwsm app -- playerctl previous
bind = $mod SHIFT, S, exec, sh -lc 'grim -g "$(slurp)" - | wl-copy'
