decoration {
  rounding = 8

  active_opacity = 1.0
  inactive_opacity = 0.95

  blur {
    enabled = true
    size = 8
    passes = 2
  }
}

animations {
  enabled = true

  bezier = standard, 0.2, 0.9, 0.1, 1.0

  animation = windows, 1, 4, standard, slide
  animation = windowsOut, 1, 4, standard, slide
  animation = border, 1, 6, standard
  animation = fade, 1, 4, standard
  animation = workspaces, 1, 5, standard, slide
}

general {
  col.active_border = rgba(89b4faff)
  col.inactive_border = rgba(45475aa0)
}
