#!/usr/bin/env bash
set -euo pipefail

# Migration: persist it87 mmio force-id config
# Host: cachy
# Generated by scripts/new-migration.sh
#
# Keep this migration idempotent. If a step truly needs elevated privileges,
# call sudo only for that step instead of running the whole migration as root.

it87_repo_url="https://github.com/frankcrawford/it87"
it87_repo_ref="60f2ef5"
target_dkms_version="v1.0-228-g60f2ef5.20260405"
modprobe_conf_path="/etc/modprobe.d/it87.conf"
modules_load_path="/etc/modules-load.d/it87.conf"
host_name="${DOTFILES_MIGRATION_HOST:-$(hostname -s 2>/dev/null || hostname)}"

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

echo "Ensuring the h2ram-mmio it87 DKMS build is installed for $host_name"

if ! command -v dkms >/dev/null 2>&1 || ! command -v git >/dev/null 2>&1; then
  echo "git and dkms are required for this migration" >&2
  exit 1
fi

if ! dkms status -m it87 -k "$(uname -r)" 2>/dev/null | grep -Fq "it87/$target_dkms_version"; then
  git clone "$it87_repo_url" "$tmp_dir/it87"
  git -C "$tmp_dir/it87" checkout "$it87_repo_ref"

  if dkms status -m it87 >/dev/null 2>&1; then
    while IFS= read -r version; do
      [[ -n "$version" ]] || continue
      sudo dkms remove -m it87 -v "$version" --all || true
    done < <(dkms status -m it87 | cut -d, -f1 | cut -d/ -f2 | sort -u)
  fi

  (
    cd "$tmp_dir/it87"
    sudo ./dkms-install.sh
  )
fi

sudo install -d /etc/modprobe.d /etc/modules-load.d
printf '%s\n' 'options it87 ignore_resource_conflict=1 mmio=1 force_id=0x8689' \
  | sudo tee "$modprobe_conf_path" >/dev/null
printf '%s\n' 'it87' | sudo tee "$modules_load_path" >/dev/null

sudo modprobe -r it87 || true
sudo modprobe it87

echo "Configured it87 with mmio=1 and force_id=0x8689"
