#!/usr/bin/env bash
set -euo pipefail

# Migration: append amdgpu ppfeaturemask to limine default cmdline
# Host: cachy
# Generated by scripts/new-migration.sh
#
# Keep this migration idempotent. If a step truly needs elevated privileges,
# call sudo only for that step instead of running the whole migration as root.

config_path="/etc/default/limine"
boot_arg="amdgpu.ppfeaturemask=0xfff7ffff"
tmp_path="$(mktemp)"

cleanup() {
  rm -f "$tmp_path"
}
trap cleanup EXIT

echo "Ensuring $boot_arg is present in KERNEL_CMDLINE[default] in $config_path"

if ! command -v limine-mkinitcpio >/dev/null 2>&1; then
  echo "limine-mkinitcpio is required for this migration" >&2
  exit 1
fi

if [[ -f "$config_path" ]]; then
  awk -v arg="$boot_arg" -f /dev/stdin "$config_path" > "$tmp_path" <<'AWK'
function trim(value) {
  sub(/^[[:space:]]+/, "", value)
  sub(/[[:space:]]+$/, "", value)
  return value
}

function has_arg(value,   parts, count, i) {
  value = trim(value)

  if (value == "") {
    return 0
  }

  count = split(value, parts, /[[:space:]]+/)
  for (i = 1; i <= count; i++) {
    if (parts[i] == arg) {
      return 1
    }
  }

  return 0
}

BEGIN {
  single_quote = sprintf("%c", 39)
}

{
  lines[NR] = $0

  if ($0 ~ /^KERNEL_CMDLINE\[default\]\+?=/) {
    rhs = trim(substr($0, index($0, "=") + 1))
    quote = "\""
    body = rhs
    operator = "="

    if ($0 ~ /^KERNEL_CMDLINE\[default\]\+=/) {
      operator = "+="
    }

    if (rhs ~ /^".*"$/) {
      body = substr(rhs, 2, length(rhs) - 2)
    } else if (rhs ~ ("^" single_quote ".*" single_quote "$")) {
      quote = single_quote
      body = substr(rhs, 2, length(rhs) - 2)
    }

    body = trim(body)
    entry_operator[NR] = operator
    entry_quote[NR] = quote
    entry_body[NR] = body

    if (operator == "+=" && target_line == 0) {
      target_line = NR
    } else if (operator == "=" && target_line == 0 && assign_line == 0) {
      assign_line = NR
    }
  }
}

END {
  if (target_line == 0) {
    target_line = assign_line
  }

  for (line_no = 1; line_no <= NR; line_no++) {
    if (!(line_no in entry_operator)) {
      print lines[line_no]
      continue
    }

    body = entry_body[line_no]

    if (line_no == target_line) {
      if (!has_arg(body)) {
        body = (body == "" ? arg : body " " arg)
      }

      print "KERNEL_CMDLINE[default]" entry_operator[line_no] entry_quote[line_no] body entry_quote[line_no]
      continue
    }

    if (target_line != 0 && body == arg) {
      continue
    }

    print lines[line_no]
  }

  if (target_line == 0) {
    print "KERNEL_CMDLINE[default]=\"" arg "\""
  }
}
AWK
else
  printf 'KERNEL_CMDLINE[default]="%s"\n' "$boot_arg" > "$tmp_path"
fi

config_changed=1
if [[ -f "$config_path" ]] && cmp -s "$tmp_path" "$config_path"; then
  config_changed=0
else
  mode="$(stat -c '%a' "$config_path" 2>/dev/null || echo 644)"
  sudo install -D -m "$mode" "$tmp_path" "$config_path"
fi

if [[ "$config_changed" -eq 1 ]]; then
  echo "Updated $config_path"
else
  echo "$config_path already contains the requested default kernel cmdline"
fi

sudo limine-mkinitcpio

echo "Regenerated initramfs and refreshed Limine entries"
