#!/usr/bin/env bash
set -euo pipefail

# Migration: install kraken liquid fan curve systemd service
# Host: cachy
# Generated by scripts/new-migration.sh
#
# Keep this migration idempotent. If a step truly needs elevated privileges,
# call sudo only for that step instead of running the whole migration as root.

repo_root="${DOTFILES_MIGRATION_REPO_ROOT:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../../.." && pwd)}"
service_name="kraken-liquid-fan-curve.service"
service_path="/etc/systemd/system/$service_name"
script_path="$repo_root/bin/cachy/kraken-liquid-fan-curve.sh"

if [[ ! -f "$script_path" ]]; then
  echo "Fan curve script not found: $script_path" >&2
  exit 1
fi

echo "Installing $service_name from $script_path"

cat <<EOF | sudo tee "$service_path" >/dev/null
[Unit]
Description=NZXT Kraken Liquid Temperature Fan Curve
After=systemd-modules-load.service
Wants=systemd-modules-load.service
ConditionPathExists=$script_path

[Service]
Type=simple
WorkingDirectory=$repo_root
ExecStart=/usr/bin/bash $script_path
Restart=always
RestartSec=5
Environment=PATH=/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now "$service_name"

echo "Installed and enabled $service_name"
