#!/usr/bin/env bash
set -euo pipefail

# Migration: Append amdgpu ppfeaturemask to limine default cmdline
# Host: cachy
# Generated by scripts/new-migration.sh
#
# Keep this migration idempotent. If a step truly needs elevated privileges,
# call sudo only for that step instead of running the whole migration as root.

config_file="/etc/default/limine"
setting_key="LIMINE_CMDLINE_DEFAULT"
desired_arg="amdgpu.ppfeaturemask=0xffffffff"

echo "Ensuring $desired_arg is present in $config_file"

if [[ ! -f "$config_file" ]]; then
  echo "Limine config not found: $config_file" >&2
  exit 1
fi

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

sudo cat "$config_file" > "$tmp_file"

python3 - "$tmp_file" "$setting_key" "$desired_arg" <<'PY'
import pathlib
import re
import shlex
import sys

config_path = pathlib.Path(sys.argv[1])
setting_key = sys.argv[2]
desired_arg = sys.argv[3]

lines = config_path.read_text().splitlines()
pattern = re.compile(rf"^({re.escape(setting_key)}=)([\"'])(.*)\2$")

for idx, line in enumerate(lines):
    match = pattern.match(line)
    if not match:
        continue

    prefix, quote, value = match.groups()
    args = shlex.split(value)

    if desired_arg not in args:
        args.append(desired_arg)

    new_value = " ".join(args)
    lines[idx] = f"{prefix}{quote}{new_value}{quote}"
    config_path.write_text("\n".join(lines) + "\n")
    break
else:
    raise SystemExit(f"{setting_key} not found in {config_path}")
PY

if sudo cmp -s "$tmp_file" "$config_file"; then
  echo "$desired_arg already present"
  exit 0
fi

sudo install -Dm644 "$tmp_file" "$config_file"
sudo limine-mkinitcpio

echo "Updated $config_file and regenerated Limine entries"
