#!/usr/bin/env bash
set -euo pipefail

# Migration: Install kraken liquid fan curve systemd service
# Host: cachy
# Generated by scripts/new-migration.sh
#
# Keep this migration idempotent. If a step truly needs elevated privileges,
# call sudo only for that step instead of running the whole migration as root.

repo_root="${DOTFILES_MIGRATION_REPO_ROOT:?missing DOTFILES_MIGRATION_REPO_ROOT}"
script_src="$repo_root/bin/cachy/kraken-liquid-fan-curve.sh"
script_dst="/usr/local/bin/kraken-liquid-fan-curve"
unit_path="/etc/systemd/system/kraken-liquid-fan-curve.service"

echo "Installing Kraken liquid fan curve script and systemd service"

if [[ ! -f "$script_src" ]]; then
  echo "Source script not found: $script_src" >&2
  exit 1
fi

sudo install -Dm755 "$script_src" "$script_dst"

tmp_unit="$(mktemp)"
trap 'rm -f "$tmp_unit"' EXIT

cat > "$tmp_unit" <<EOF
[Unit]
Description=Apply Kraken liquid fan curve
After=multi-user.target

[Service]
Type=oneshot
ExecStart=$script_dst

[Install]
WantedBy=multi-user.target
EOF

sudo install -Dm644 "$tmp_unit" "$unit_path"
sudo systemctl daemon-reload
sudo systemctl enable --now kraken-liquid-fan-curve.service

echo "Installed and enabled kraken-liquid-fan-curve.service"
