#!/usr/bin/env bash
set -euo pipefail

# Migration: Persist it87 mmio force id config
# Host: cachy
# Generated by scripts/new-migration.sh
#
# Keep this migration idempotent. If a step truly needs elevated privileges,
# call sudo only for that step instead of running the whole migration as root.

modprobe_file="/etc/modprobe.d/it87.conf"
desired_line="options it87 force_id=0x8628 ignore_resource_conflict=1"

echo "Ensuring it87 module options are persisted"

if sudo test -f "$modprobe_file" && sudo grep -Fxq "$desired_line" "$modprobe_file"; then
  echo "it87 module options already configured"
  exit 0
fi

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

if sudo test -f "$modprobe_file"; then
  sudo cat "$modprobe_file" > "$tmp_file"
fi

printf '%s\n' "$desired_line" >> "$tmp_file"
sudo install -Dm644 "$tmp_file" "$modprobe_file"

echo "Configured $modprobe_file"
