# k3d needs bridged traffic to pass through iptables so Kubernetes Service
# ClusterIPs work from pods. See https://k3d.io/faq/faq/#pods-fail-to-start-with-cni-plugin-not-initialized
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
